sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo

script:
  - cargo check --benches
  - cargo test --features "vector-tests"
  - cargo test --features "ring-resolver vector-tests"
  - cargo test --features "ring-accelerated vector-tests"
  - cargo test --features "hfs vector-tests"
  - cargo test --features "ring-resolver hfs vector-tests"
  - cargo test --features "ring-accelerated hfs vector-tests"
  - cargo test --no-default-features

