sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo

script:
  - cargo check --benches
  - cargo test --features "vector-tests"
  - cargo test --features "ring-resolver vector-tests"
  - cargo test --features "ring-accelerated vector-tests"
  - cargo test --features "hfs pqclean_kyber1024 vector-tests"
  - cargo test --features "ring-resolver hfs pqclean_kyber1024 vector-tests"
  - cargo test --no-default-features

